eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
   prefer-ip-address: true
#    hostname: localhost
microservice:
  payment-service:
    endpoints:
      save:
        uri: http://PAYMENT-SERVICE/payment/savePayment
      paymentid:
        uri: http://PAYMENT-SERVICE/payment/{id}
  order-service:
    endpoints:
      save:
        uri: http://ORDER-SERVICE/order/saveOrder
      get:
        uri: http://ORDER-SERVICE/order/{id}
        
